apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  namespace: sink
  name: sink-kctr
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: sink-kafkaconnect
spec:
  class: com.altinity.clickhouse.sink.connector.ClickHouseSinkConnector
  tasksMax: 1
  config:
    topics: "${TOPICS}"
    clickhouse.topic2table.map: "${TOPICS_TABLE_MAP}"
    clickhouse.server.url: "${CLICKHOUSE_HOST}"
    clickhouse.server.user: "${CLICKHOUSE_USER}"
    clickhouse.server.password: "${CLICKHOUSE_PASSWORD}"
    clickhouse.server.database: "${CLICKHOUSE_DATABASE}"
    clickhouse.server.port: "${CLICKHOUSE_PORT}"
    clickhouse.table.name: "${CLICKHOUSE_TABLE}"

    store.kafka.metadata: "false"
    topic.creation.default.partitions: "6"

    store.raw.data: "false"
    store.raw.data.column: "raw_data"

    replacingmergetree.delete.column: "_sign"

    auto.create.tables: "true"
    schema.evolution: "false"

    deduplication.policy: "off"

    metrics.enable: "false"

    key.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"

    key.converter.schema.registry.url : "http://schema-registry.registry:8081"
    value.converter.schema.registry.url: "http://schema-registry.registry:8081"
