name: Kafka - Build

on: 
  workflow_call:
    inputs:
      IMAGE_TAG:
        description: "Kafka connector version"
        required: true
        type: string
        default: "latest"

env:
  # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
  IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

jobs:
  build-kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Update Kafka version
        working-directory: sink-connector
        if: ${{ github.event_name == 'release' }}
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Update Lightweight version
        working-directory: sink-connector-lightweight
        if: ${{ github.event_name == 'release' }}
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Setup env
        working-directory: sink-connector
        run: echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_ENV"

      - name: Build with Maven (Kafka version)
        working-directory: sink-connector
        run: mvn -B package install -DskipTests=true --file pom.xml

      - name: Build the Kafka Docker image
        working-directory: sink-connector
        run: |
          docker build . --file docker/Dockerfile-sink-on-debezium-base-image --tag altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-kafka
          docker save altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-kafka | gzip > clickhouse-sink-connector_${{ env.IMAGE_TAG }}-kafka.tar.gz

      - name: Upload Kafka Docker tar
        uses: actions/upload-artifact@v3
        with:
          name: clickhouse-sink-connector_${{ env.IMAGE_TAG }}-kafka.tar.gz
          path: sink-connector/clickhouse-sink-connector_${{ env.IMAGE_TAG }}-kafka.tar.gz

      - name: Update sink connector jar file version in sink-connector-lightweight pom.xml
        working-directory: sink-connector-lightweight
        run:  mvn versions:set-property -Dproperty=sink-connector-library-version -DnewVersion=${{ env.PROJECT_VERSION }}

      - name: Build with Maven (Lightweight version)
        working-directory: sink-connector-lightweight
        run:  mvn -B package -DskipTests=true --file pom.xml

      - name: Build with Go
        working-directory: sink-connector-client
        run: CGO_ENABLED=0 go build

      - name: Build the Lightweight Docker image
        run: |
          docker build . --file sink-connector-lightweight/Dockerfile --tag altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-lt
          docker save altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-lt | gzip > clickhouse-sink-connector_${{ env.IMAGE_TAG }}-lt.tar.gz

      - name: Upload Lightweight Docker tar
        uses: actions/upload-artifact@v3
        with:
          name: clickhouse-sink-connector_${{ env.IMAGE_TAG }}-lt.tar.gz
          path: clickhouse-sink-connector_${{ env.IMAGE_TAG }}-lt.tar.gz

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Kafka Docker image
        run: |
          docker image push altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-kafka
          docker image push altinityinfra/clickhouse-sink-connector:${{ env.IMAGE_TAG }}-lt
        if: ${{ env.DOCKER_USERNAME != '' }}
