name: Publish Release

on: 
  workflow_call:
    inputs: 
      release_tag:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
        default: true
      draft:
        required: true
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

env:
  release_tag: ${{ inputs.release_tag }}

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull test images
        if: ${{ inputs.prerelease == false && inputs.draft == false}}
        run: |
          docker pull altinityinfra/clickhouse-sink-connector:$release_tag-test-kafka
          docker pull altinityinfra/clickhouse-sink-connector:$release_tag-test-lt

      - name: Tag images
        if: ${{ inputs.prerelease == false && inputs.draft == false}}
        run: |
          docker image tag altinityinfra/clickhouse-sink-connector:$release_tag-test-kafka altinity/clickhouse-sink-connector:$release_tag-kafka
          docker image tag altinityinfra/clickhouse-sink-connector:$release_tag-test-lt altinity/clickhouse-sink-connector:$release_tag-lt

      - name: Push images
        if: ${{ inputs.prerelease == false && inputs.draft == false}}
        run: |
          docker push altinity/clickhouse-sink-connector:$release_tag-kafka
          docker push altinity/clickhouse-sink-connector:$release_tag-lt

      - name: Update Docker links
        if: ${{ inputs.prerelease == false && inputs.draft == false}}
        run: sed -i "s/release_tag/$release_tag/" release_notes.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.env.release_tag }}
          release_name: Release v${{ github.env.release_tag }}
          prerelease: ${{ inputs.prerelease }}
          draft: ${{ inputs.draft }}
          body-path: release_notes.md

      - name: Download jar files
        uses: actions/download-artifact@v3
        with:
          name: |
            clickhouse-sink-connector-kafka-${{ github.env.release_tag }}.jar
            clickhouse-sink-connector-lt-${{ github.env.release_tag }}.jar

      - name: Upload jar files to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: |
            clickhouse-sink-connector-kafka-${{ github.env.release_tag }}.jar
            clickhouse-sink-connector-lt-${{ github.env.release_tag }}.jar
