name: Kafka Sink Connector - Pull Request Pipeline

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - '**'

jobs:
  build-kafka-lightweight:
    uses: ./.github/workflows/docker-build.yml
    with:
      IMAGE_TAG: ${{ github.event.number }}-${{ github.sha }}
    secrets: inherit

  testflows-kafka:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/testflows-sink-connector-kafka.yml
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-kafka
    secrets: inherit

  testflows-lightweight:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/testflows-sink-connector-lightweight.yml
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt
    secrets: inherit

  java-tests-kafka:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-kafka-tests.yml

  java-tests-lightweight:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-lightweight-tests.yml
